---
server:
  port: 80

app:
  datasource:
    jdbc-url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    dialect: org.hibernate.dialect.PostgreSQLDialect
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

# JWT configuration
application:
  jwt:
    secretKey: ${JWT_SECRET_KEY}
    tokenPrefix: 'Bearer '
    tokenExpirationAfterDays: ${JWT_EXPIRATION_DAYS}


spring:
  flyway:
    out-of-order: true
